spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect
jwt:
  secret: ${JWT_SECRET_KEY}
  access-name: ${JWT_ACCESS_NAME}
  access-expiration: ${JWT_ACCESS_EXPIRATION}